# Generated by Django 4.2.3 on 2023-07-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
